### ISSUE TITLE
Account Address from Generate/Import dose not match the one in the Polkadot browser extension.

### ISSUE THREAD

**Issue by shekohex** [webb-tools/cli#1]
Currently, we have an issue where the account that got generated using the CLI, the public address is not the same form as the one in the Polkadot browser extension.

Also, if you imported an account using the Mnemonic Seed Phrase, the resulted address is not the same as the one inside the browser extension.

Example:

I first generated this account using the Polkadot browser extension that generated the following seed phrase:
```
sting road differ cement medal place blouse captain furnace flight evoke glance
```
Password used for this `test` account: `123456`
Generated Account Address: `5Ctz5L7deD4bn4x12FyFfPfEumrDNjHhf2vHJrygxqiVTmLK`

Now from the CLI, I did the following:

```bash
$ webb account import -a test -p 123456 -m "sting road differ cement medal place blouse captain furnace flight evoke glance"
```

The output:
```
Importing account with test
Account Imported:
test: 5Cd9BKVJENu9asa8RDQpNFUCL5KrDaMRFjhyRx9GKtTB8cCi

To set this account as default:
    $ webb default test
```
Notice the generated address from the CLI? `5Cd9BKVJENu9asa8RDQpNFUCL5KrDaMRFjhyRx9GKtTB8cCi`

**Comment by drewstone** [comment]
It is likely due to SS58? Can you post examples?

**Comment by shekohex** [comment]
> It is likely due to SS58? Can you post examples?

I updated the issue with an example.

**Comment by drewstone** [comment]
Linking: https://github.com/paritytech/substrate-subxt/issues/233

**Comment by shekohex** [comment]
Well, turns out that the Polkadot UI does not account for the password during the account seed generation.

https://github.com/polkadot-js/extension/blob/8d351e06c4468436038d04178474832977c2af6c/packages/extension-base/src/background/handlers/Extension.ts#L280-L287

the password is used to protect the Keystore, nothing else!

Here when I tried to set the password to `None` instead of `Some(password)` the resulted account address now matches the one generated from the Polkadot browser extension.

https://github.com/webb-tools/cli/blob/20235c33330598ad1ff697624aedb2e1e42d1eee/src/keystore.rs#L24-L26

I guess with that, we could close this issue now.
